platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'WebRTCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebRTCDemo
  pod 'GoogleWebRTC'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'

  target 'WebRTCDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
