# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebRTCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebRTCDemo

  pod 'WebRTC-SDK', '=125.6422.04'
  pod 'Socket.IO-Client-Swift', '16.1.0'
  pod 'FlexLayout'
  pod 'PinLayout'

end


target 'WebRTCDemoScreenBroadcast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebRTCDemoScreenBroadcast
 
  # the extension will simply reuse signaling info that the main app already did and save to userdefaults
  
  pod 'WebRTC-SDK', '=125.6422.04'

end